apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-application
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: film-application
  template:
    metadata:
      labels:
        app: film-application
    spec:
      containers:
        - name: film-app-container
          image: itsvictorfy/final-proj:aca930b
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: test
            - name: DB_DATABASE
              value: moviesDB
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: sqlAdmin


---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: web-server