extraScrapeConfigs: |
  - job_name: 'Jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins.cicd.svc.cluster.local:8080']
    metric_relabel_configs:
    - action: replace
      source_labels: [exported_job]
      target_label: jenkins_job
    - action: labeldrop
      regex: exported_job