apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: postgresdb
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-postgresdb
    