apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-postgresdb-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  replicas: 2
  serviceName: postgresdb
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: h3xbar/final-proj:psgrsql1
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret-credentials
          volumeMounts:
            - mountPath: /data/db
              name: db-data  
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: bW92aWVzZGI=   # Base64-encoded value: "moviesdb"
  POSTGRES_USER: cG9zdGdyZXM=    # Base64-encoded value: "admin"
  POSTGRES_PASSWORD: c3FsQWRtaW4=   # Base64-encoded value: "sqlAdmin"

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  selector:
    app: postgresdb
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
